In [3]:
# 1. Flowchart: Print_values
# Ask users to input 3 numbers to assign a,b,c
a=float(input("please input the 1st number as the value of a:"))
b=float(input("please input the 2nd number as the value of b:"))
c=float(input("please input the 3rd number as the value of c:"))
# Compare number size for a,b,c
if(a>b):
    if(b>c):
        # Based on the number size of a,b,c, assign x,y,z 
        x=a
        y=b
        z=c
        # Output the value of (x+y-10*z)
        print("x+y-10*z = ", x+y-10*z)
    elif(a>c):
        x=a
        y=c
        z=b
        print("x+y-10*z = ", x+y-10*z)
    else:
        x=c
        y=a
        z=b
        print("x+y-10*z = ", x+y-10*z)
elif(b>c):
    print(None)
else:    
    x=c
    y=b
    z=a
    print("x+y-10*z = ", x+y-10*z)

please input the 1st number as the value of a:10
please input the 2nd number as the value of b:5
please input the 3rd number as the value of c:1
x+y-10*z =  5.0


In [29]:
# 2. Continuous celing function
from math import *
import numpy as np
# Ask users to input the range and the item number to create a random list
M=int(input("Please input the range of positive intergers (>0):"))
N=int(input("Please input the number of positive intergers:"))
list=np.random.randint(1,M+1,N)
print("The random list is shown below:\n",list)
# Define a function F(x) to get the value of F(x) = F(ceil(x/3)) + 2x, where F(1) = 1
y=0
def F(x):
    if(x==1):
        return 1
    else:
        y=F(ceil(x/3))+2*x
        return y
# Use a "for" loop and the function F(x) to get the value of F(list[i])
for i in range(N):
    print ("x=", list[i],",F(x)=", F(list[i]))

Please input the range of positive intergers (>0):50
Please input the number of positive intergers:9
The random list is shown below:
 [40 49 27  5 40  4 42 15 24]
x= 40 ,F(x)= 123
x= 49 ,F(x)= 149
x= 27 ,F(x)= 79
x= 5 ,F(x)= 15
x= 40 ,F(x)= 123
x= 4 ,F(x)= 13
x= 42 ,F(x)= 127
x= 15 ,F(x)= 45
x= 24 ,F(x)= 71


In [9]:
# 3. Dice Rolling
# 3.1 Find_number_of_ways
# Set the total number of dices(D)
D=10
# Define a function to calculate the probability of sum X for D dices
def Prob(D,X):
    prob=0
    # For each dice, the probability to toss“0/1/2/3/4/5/6” is (1/6).
    # When sum X is equal to the number of dices(D), the probability is (1/6)^D
    if X==D:
        return pow(1/6,D)
    # When sum X is smaller than D or larger than 6D, the probability is 0
    if X<D or X>6*D:
        return 0
    else:
    # The probability of sum X for D dices is equal to the probability of 
    # sum (X-a) for (D-1) dices, where "a" is the potint of the last dice, belonging to 1-6.
    # Inspired from https://blog.csdn.net/yue_luo_/article/details/95517498
        for i in range(6):
            prob += Prob(D-1, X-i-1)
        return prob/6
# Define a function to calculate the number of ways to reach sum X
def Find_number_of_ways(X):
    # The total number of ways is (6^10). The number of ways for each sum(X) is probability*(6^10).
    print("The number of ways is",round(Prob(D,X)*(6**10)))
# Ask users to input a sum X and find its number of ways
x=int(input("Please input a sum X:"))
Find_number_of_ways(x)

# 3.2 List: Number_of_ways
# Use a "for" loop to calculate 51 times to get Number_of_ways for sum X, 10-60 respectively.
# Consume around 2.5 min
Number_of_ways=[]
for i in range(10,61):
    ways_number=round(Prob(D,i)*(6**10))
    Number_of_ways.append(ways_number)
print("Number of ways are listed below\n", Number_of_ways)
print(Number_of_ways.index(max(Number_of_ways))+10,"yields the maximum of Number_of_ways")

Please input a sum X:13
The number of ways is 220
Number of ways are listed below
 [1, 10, 55, 220, 715, 2002, 4995, 11340, 23760, 46420, 85228, 147940, 243925, 383470, 576565, 831204, 1151370, 1535040, 1972630, 2446300, 2930455, 3393610, 3801535, 4121260, 4325310, 4395456, 4325310, 4121260, 3801535, 3393610, 2930455, 2446300, 1972630, 1535040, 1151370, 831204, 576565, 383470, 243925, 147940, 85228, 46420, 23760, 11340, 4995, 2002, 715, 220, 55, 10, 1]
35 yields the maximum of Number_of_ways


In [10]:
# 4.Dynamic programming
import numpy as np
import math
# 4.1 Random_integer function
# Ask users to decide the size of an array and create an array
N=int(input("Please input the number of elements to create an array:"))
Random_interger=np.random.randint(0,11,N)
print(Random_interger)

# 4.2 Sum_averages function
# Define a function to calculate the sum of subset average(SA)
def Sum_averages(array):
    # For an array with N elements, sum of all subset average with n elements (n<=N) is 
    # equal to (array.sum() * C(N-1,n-1)/n).Here use a "for" loop to achieve the sum of C(N-1,n-1)/n 
    # for all subsets, whose element number increasing from 1 to N
    # Discussed with Wenting Yuan and inspired from https://www.geeksforgeeks.org/sum-average-subsets/
    SA=0
    for i in range(0,len(array)):
        SA+=(math.factorial(len(array)-1)/math.factorial(len(array)-1-i)/math.factorial(i))/(i+1)
    SA=SA*array.sum()
    return SA
print("The Sum_averages for each subset is:\n", Sum_averages(Random_interger))

# 4.3 Total_sum_set function
import matplotlib.pyplot as plt
Total_sum_set=[]
# Use a "for" loop to calculate Sum_averages for random list with N increasing from 1 to 100
# Each result of Sum_averages(np.random.randint(0,11,j+1)) appended in the Total_sum_set
for j in range(100):
    sum=Sum_averages(np.random.randint(0,11,j+1))
    Total_sum_set.append(sum)
print("Sum_averages with element number increasing from 1 to 100 are shown below:\n",Total_sum_set)
# Plot Total_sum_set
x=np.arange(1,101,1)
y=Total_sum_set
plt.plot(x, y, ls="-", lw=2, label="plot line:Total_sum_set vs. len(Random_interger)")
plt.legend()
plt.xlabel("Element number of an array")
plt.ylabel("Sum_averages")
plt.show()



Please input the number of elements to create an array:5
[ 5  6 10  5  1]
The Sum_averages for each subset is:
 167.4
Sum_averages with element number increasing from 1 to 100 are shown below:
 [7.0, 13.5, 49.0, 63.75, 229.4, 304.5, 598.7142857142857, 1816.875, 1816.8888888888891, 4194.3, 11165.454545454546, 23887.499999999996, 32764.0, 97127.78571428572, 148543.73333333334, 344058.75, 701615.3529411765, 1441786.5, 2207524.2105263155, 5976877.5, 10585619.333333332, 22687366.227272727, 40119424.782608695, 75497467.5, 153008205.35999998, 340706535.2307692, 656175554.2222221, 1476395002.5000002, 2813944085.2413793, 4402341474.3, 9213397582.290323, 22682796026.71875, 36702447797.90909, 86909926455.17647, 177688932697.9143, 299693273538.74994, 676051068424.919, 1511828488186.5, 2960223613237.693, 6102289534151.251, 11102385704855.049, 27540148390954.5, 45616947533771.19, 104353649036188.95, 206414982921141.88, 336546167806214.3, 655776807442906.8, 1477743627730938.5, 2768794668868080.0, 632

In [13]:
# 5. Path counting
# 5.1 Create a matrix
import numpy as np
# Ask users to decide the size of a matrix and create a matrix
N = int(input("Please input the number of rows:"))
M = int(input("Please input the number of columns:"))
arr=np.random.randint(2,size=(N,M))
arr[0,0]=1
arr[N-1,M-1]=1
print(arr)

# 5.2 Count_path function
# Define a function Count_path(matrix,a,b) to count the pathway for a specific matrix, 
# where "a" is row number, "b" is column number.
# Regard each element as a point, the number of pathways to a point is equal to 
# the pathway number of its upper point plus that of its left point, because 
# only moving either rightward or downward is allowed.
# Inspired from https://www.geeksforgeeks.org/count-number-of-ways-to-reach-destination-in-a-maze/?ref=rp
def Count_path(matrix,a,b):
    # Substract 1 from each element for counting purposes, and the matrix is
    # refilled by -1 or 0, which were 0 or 1 before, respectively.
    matrix=np.add(matrix,-1)
    # Initialize the leftmost column
    for i in range(a):
        # If meet a blockage, break the loop
        if(matrix[i,0] != 0):
            break
        # If meet an access, each element plus 1, which means 
        # the number of pathways from entrance[0,0] to the element[i,0] is 1
        else:
            matrix[i,0] +=1
    # Initialize the uppermost row, whose solution is similar to the leftmost column      
    for j in range(b):
        if(matrix[0,j] != 0):
            break
        else:
            matrix[0,j] +=1
    # Since the pathway number of a point is equal to the pathway number of 
    # its upper point plus that of its left point,
    # two "for" loops were used to count the pathways for each point, up to the last element[a-1,b-1]
    for i in range(1,a,1):
        for j in range(1,b,1):
            if(matrix[i,j] != 0):
                continue
            if(matrix[i-1,j] >0):
                matrix[i,j] += matrix[i-1,j]
            if(matrix[i,j-1] >0):
                matrix[i,j] += matrix[i,j-1]
    Count_path = matrix[a-1,b-1]
    # Return the pathway number of the last element[a-1,b-1]
    if (Count_path >= 0):
        return Count_path
    # If the value of last element[a-1,b-1] is smaller than zero, return 0
    else:
        return 0
# Print the pathway number of the matrix in 5.1
print("The Count_path value of the matrix above is",Count_path(arr,N,M))

# 5.3 Count_path function
# Calculate the mean pathway number for 1000 runs by refilling new random matrix
sum_path=0
for k in range(1000):
    sum_path += Count_path(np.random.randint(2,size=(10,8)),10,8)
print("The mean of Count_path for matrixes with size(10,8) from the 1000 runs is\n", sum_path/1000)    

Please input the number of rows:6
Please input the number of columns:7
[[1 1 1 0 0 0 0]
 [0 1 1 0 0 1 1]
 [1 1 1 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 1 1 1]]
The Count_path value of the matrix above is 0
The mean of Count_path for matrixes with size(10,8) from the 1000 runs is
 0.106
